//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix invalide..
        /// </summary>
        public static string App_Case_Mauvais {
            get {
                return ResourceManager.GetString("App_Case_Mauvais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur une touche pour revenir au menu....
        /// </summary>
        public static string Back_To_Menu {
            get {
                return ResourceManager.GetString("Back_To_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGER LA LANGUE.
        /// </summary>
        public static string Chg_Lang {
            get {
                return ResourceManager.GetString("Chg_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination (Chemin complet) : .
        /// </summary>
        public static string Create_Job_Arg_Dest {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        public static string Create_Job_Arg_Name {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source (Chemin complet) : .
        /// </summary>
        public static string Create_Job_Arg_Source {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (1 = Complet, 2 = Différentiel) : .
        /// </summary>
        public static string Create_Job_Arg_TypeSave {
            get {
                return ResourceManager.GetString("Create_Job_Arg_TypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de créer la sauvegarde. Vérifiez les erreurs ci-dessus..
        /// </summary>
        public static string Create_Job_Fail {
            get {
                return ResourceManager.GetString("Create_Job_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVELLE SAUVEGARDE.
        /// </summary>
        public static string Create_Job_Header {
            get {
                return ResourceManager.GetString("Create_Job_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sauvegarde créée avec succès !&quot;.
        /// </summary>
        public static string Create_Job_Succes {
            get {
                return ResourceManager.GetString("Create_Job_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur actuelle :.
        /// </summary>
        public static string Current_Value {
            get {
                return ResourceManager.GetString("Current_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID du job à supprimer :.
        /// </summary>
        public static string Delete_Job_ID {
            get {
                return ResourceManager.GetString("Delete_Job_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job supprimé..
        /// </summary>
        public static string Delete_Job_Succes {
            get {
                return ResourceManager.GetString("Delete_Job_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Tous les champs doivent être remplis.
        /// </summary>
        public static string Erreur_Creation_Blank {
            get {
                return ResourceManager.GetString("Erreur_Creation_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Les chemins source et destination doivent être valides (ex: C:\\Dossier)..
        /// </summary>
        public static string Erreur_Creation_Chemin {
            get {
                return ResourceManager.GetString("Erreur_Creation_Chemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum de jobs atteint..
        /// </summary>
        public static string Erreur_Creation_Trop_Nombreux {
            get {
                return ResourceManager.GetString("Erreur_Creation_Trop_Nombreux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution globale lancée....
        /// </summary>
        public static string Get_Job_All_Try {
            get {
                return ResourceManager.GetString("Get_Job_All_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez l&apos;ID à exécuter (ou &apos;all&apos; pour tout) : .
        /// </summary>
        public static string Get_Job_Arg_ID {
            get {
                return ResourceManager.GetString("Get_Job_Arg_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération terminée..
        /// </summary>
        public static string Get_Job_End {
            get {
                return ResourceManager.GetString("Get_Job_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution du job {0}....
        /// </summary>
        public static string Get_Job_Running {
            get {
                return ResourceManager.GetString("Get_Job_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Header_Dest {
            get {
                return ResourceManager.GetString("Header_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Header_Id {
            get {
                return ResourceManager.GetString("Header_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Header_Source {
            get {
                return ResourceManager.GetString("Header_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Header_Type {
            get {
                return ResourceManager.GetString("Header_Type", resourceCulture);
            }
        }

        public static string Menu_Option_Home
        {
            get
            {
                return ResourceManager.GetString("Menu_Option_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lister les travaux.
        /// </summary>
        public static string Menu_Option1 {
            get {
                return ResourceManager.GetString("Menu_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un travail.
        /// </summary>
        public static string Menu_Option2 {
            get {
                return ResourceManager.GetString("Menu_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécuter un travail.
        /// </summary>
        public static string Menu_Option3 {
            get {
                return ResourceManager.GetString("Menu_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer un travail.
        /// </summary>
        public static string Menu_Option4 {
            get {
                return ResourceManager.GetString("Menu_Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Menu_OptionExit {
            get {
                return ResourceManager.GetString("Menu_OptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Menu_OptionSettings {
            get {
                return ResourceManager.GetString("Menu_OptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU PRINCIPAL.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune travail de sauvegarde trouvé..
        /// </summary>
        public static string Msg_NoJobs {
            get {
                return ResourceManager.GetString("Msg_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyer sur Entrée pour revenir au menu....
        /// </summary>
        public static string Msg_Return {
            get {
                return ResourceManager.GetString("Msg_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string None2 {
            get {
                return ResourceManager.GetString("None2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour au menu principal.
        /// </summary>
        public static string SettingsFlow_BackMenu {
            get {
                return ResourceManager.GetString("SettingsFlow_BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du logiciel (ou vide pour aucun) : .
        /// </summary>
        public static string SettingsFlow_BSoftWareName {
            get {
                return ResourceManager.GetString("SettingsFlow_BSoftWareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logiciel métier modifié avec succès !.
        /// </summary>
        public static string SettingsFlow_BSoftWareSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_BSoftWareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- MODIFICATION DE LA LANGUE ---.
        /// </summary>
        public static string SettingsFlow_Changementlang {
            get {
                return ResourceManager.GetString("SettingsFlow_Changementlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre choix :.
        /// </summary>
        public static string SettingsFlow_Choice {
            get {
                return ResourceManager.GetString("SettingsFlow_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix invalide. Appuyez sur une touche....
        /// </summary>
        public static string SettingsFlow_ChoixErreur {
            get {
                return ResourceManager.GetString("SettingsFlow_ChoixErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quel paramètre souhaitez-vous modifier ?.
        /// </summary>
        public static string SettingsFlow_Choixmodif {
            get {
                return ResourceManager.GetString("SettingsFlow_Choixmodif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyer sur une touche pour continuer ....
        /// </summary>
        public static string SettingsFlow_Continue {
            get {
                return ResourceManager.GetString("SettingsFlow_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions Crypto.
        /// </summary>
        public static string SettingsFlow_Crypto {
            get {
                return ResourceManager.GetString("SettingsFlow_Crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions actuelles :.
        /// </summary>
        public static string SettingsFlow_Encryp_Exten {
            get {
                return ResourceManager.GetString("SettingsFlow_Encryp_Exten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez les extensions séparées par des virgules (ex: .txt,.doc,.pdf) : .
        /// </summary>
        public static string SettingsFlow_EncryptExtenChoice {
            get {
                return ResourceManager.GetString("SettingsFlow_EncryptExtenChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions crypto modifiées avec succès !.
        /// </summary>
        public static string SettingsFlow_EncryptSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_EncryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string SettingsFlow_Language {
            get {
                return ResourceManager.GetString("SettingsFlow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue modifiée avec succès !.
        /// </summary>
        public static string SettingsFlow_LanguageSucessfull {
            get {
                return ResourceManager.GetString("SettingsFlow_LanguageSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Log.
        /// </summary>
        public static string SettingsFlow_LogFormat {
            get {
                return ResourceManager.GetString("SettingsFlow_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format de log modifié avec succès !.
        /// </summary>
        public static string SettingsFlow_LogFormatSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_LogFormatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- MODIFICATION DU LOGICIEL MÉTIER ---.
        /// </summary>
        public static string SettingsFlow_ModifBusinesSoftWare {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifBusinesSoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- MODIFICATION DES EXTENSIONS CRYPTO ---.
        /// </summary>
        public static string SettingsFlow_ModifEncrypt {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- MODIFICATION DU FORMAT DE LOG ---.
        /// </summary>
        public static string SettingsFlow_ModifLogFormat {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- PARAMÈTRES ---.
        /// </summary>
        public static string SettingsFlow_Parameters {
            get {
                return ResourceManager.GetString("SettingsFlow_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorités.
        /// </summary>
        public static string SettingsFlow_Priorities {
            get {
                return ResourceManager.GetString("SettingsFlow_Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logiciel métier.
        /// </summary>
        public static string SettingsFlow_SoftwareBuis {
            get {
                return ResourceManager.GetString("SettingsFlow_SoftwareBuis", resourceCulture);
            }
        }
    }
}
