//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les jobs sont terminés.
        /// </summary>
        public static string Alljob_Completed {
            get {
                return ResourceManager.GetString("Alljob_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix invalide..
        /// </summary>
        public static string App_Case_Mauvais {
            get {
                return ResourceManager.GetString("App_Case_Mauvais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur une touche pour revenir au menu....
        /// </summary>
        public static string Back_To_Menu {
            get {
                return ResourceManager.GetString("Back_To_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulé: Job.
        /// </summary>
        public static string Cancel_job {
            get {
                return ResourceManager.GetString("Cancel_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [ERREUR] Le logiciel métier.
        /// </summary>
        public static string CanLaunch_Erreur1 {
            get {
                return ResourceManager.GetString("CanLaunch_Erreur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est détecté..
        /// </summary>
        public static string CanLaunch_Erreur1_1 {
            get {
                return ResourceManager.GetString("CanLaunch_Erreur1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  &gt; Veuillez fermer le logiciel métier..
        /// </summary>
        public static string Canlaunch_Erreur2 {
            get {
                return ResourceManager.GetString("Canlaunch_Erreur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  &gt; Appuyez sur [ENTRÉE] pour valider la fermeture et reprendre....
        /// </summary>
        public static string CanLaunch_Erreur3 {
            get {
                return ResourceManager.GetString("CanLaunch_Erreur3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action interdite : Logiciel métier détecté..
        /// </summary>
        public static string CanLaunch_ErreurMetier {
            get {
                return ResourceManager.GetString("CanLaunch_ErreurMetier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [REPRISE] Logiciel métier fermé. Lancement....
        /// </summary>
        public static string CanLaunch_Resume {
            get {
                return ResourceManager.GetString("CanLaunch_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CHANGER LA LANGUE.
        /// </summary>
        public static string Chg_Lang {
            get {
                return ResourceManager.GetString("Chg_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination (Chemin complet) : .
        /// </summary>
        public static string Create_Job_Arg_Dest {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom :.
        /// </summary>
        public static string Create_Job_Arg_Name {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source (Chemin complet) : .
        /// </summary>
        public static string Create_Job_Arg_Source {
            get {
                return ResourceManager.GetString("Create_Job_Arg_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type (1 = Complet, 2 = Différentiel) : .
        /// </summary>
        public static string Create_Job_Arg_TypeSave {
            get {
                return ResourceManager.GetString("Create_Job_Arg_TypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de créer la sauvegarde. Vérifiez les erreurs ci-dessus..
        /// </summary>
        public static string Create_Job_Fail {
            get {
                return ResourceManager.GetString("Create_Job_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NOUVELLE SAUVEGARDE.
        /// </summary>
        public static string Create_Job_Header {
            get {
                return ResourceManager.GetString("Create_Job_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Sauvegarde créée avec succès !&quot;.
        /// </summary>
        public static string Create_Job_Succes {
            get {
                return ResourceManager.GetString("Create_Job_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur actuelle :.
        /// </summary>
        public static string Current_Value {
            get {
                return ResourceManager.GetString("Current_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination (chemin complet, ou vide pour remplacer) : .
        /// </summary>
        public static string Decrypt_Arg_Dest {
            get {
                return ResourceManager.GetString("Decrypt_Arg_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe : .
        /// </summary>
        public static string Decrypt_Arg_Password {
            get {
                return ResourceManager.GetString("Decrypt_Arg_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier chiffré (chemin complet) : .
        /// </summary>
        public static string Decrypt_Arg_Source {
            get {
                return ResourceManager.GetString("Decrypt_Arg_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors du déchiffrement (mot de passe incorrect ou fichier invalide)..
        /// </summary>
        public static string Decrypt_Error {
            get {
                return ResourceManager.GetString("Decrypt_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier chiffré introuvable..
        /// </summary>
        public static string Decrypt_FileNotFound {
            get {
                return ResourceManager.GetString("Decrypt_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DÉCHIFFREMENT DE FICHIER.
        /// </summary>
        public static string Decrypt_Header {
            get {
                return ResourceManager.GetString("Decrypt_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier déchiffré avec succès en.
        /// </summary>
        public static string Decrypt_Success {
            get {
                return ResourceManager.GetString("Decrypt_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID du job à supprimer :.
        /// </summary>
        public static string Delete_Job_ID {
            get {
                return ResourceManager.GetString("Delete_Job_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job supprimé..
        /// </summary>
        public static string Delete_Job_Succes {
            get {
                return ResourceManager.GetString("Delete_Job_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un fichier a rencontré une erreur pendant le chiffrement..
        /// </summary>
        public static string EncryptionError {
            get {
                return ResourceManager.GetString("EncryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Tous les champs doivent être remplis.
        /// </summary>
        public static string Erreur_Creation_Blank {
            get {
                return ResourceManager.GetString("Erreur_Creation_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Les chemins source et destination doivent être valides (ex: C:\\Dossier)..
        /// </summary>
        public static string Erreur_Creation_Chemin {
            get {
                return ResourceManager.GetString("Erreur_Creation_Chemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre maximum de jobs atteint..
        /// </summary>
        public static string Erreur_Creation_Trop_Nombreux {
            get {
                return ResourceManager.GetString("Erreur_Creation_Trop_Nombreux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Erreur Job.
        /// </summary>
        public static string Erreur_job {
            get {
                return ResourceManager.GetString("Erreur_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fichiers.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier a été correctement chiffré en:.
        /// </summary>
        public static string FileEncrypted {
            get {
                return ResourceManager.GetString("FileEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un fichier a chiffré n&apos;a pas été trouvé..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution globale lancée....
        /// </summary>
        public static string Get_Job_All_Try {
            get {
                return ResourceManager.GetString("Get_Job_All_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez l&apos;ID à exécuter (ou &apos;all&apos; pour tout) : .
        /// </summary>
        public static string Get_Job_Arg_ID {
            get {
                return ResourceManager.GetString("Get_Job_Arg_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opération terminée..
        /// </summary>
        public static string Get_Job_End {
            get {
                return ResourceManager.GetString("Get_Job_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution du job {0}....
        /// </summary>
        public static string Get_Job_Running {
            get {
                return ResourceManager.GetString("Get_Job_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string Header_Dest {
            get {
                return ResourceManager.GetString("Header_Dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID.
        /// </summary>
        public static string Header_Id {
            get {
                return ResourceManager.GetString("Header_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string Header_Source {
            get {
                return ResourceManager.GetString("Header_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Header_Type {
            get {
                return ResourceManager.GetString("Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécution annulée.
        /// </summary>
        public static string JobViewModel_Cancelexecution {
            get {
                return ResourceManager.GetString("JobViewModel_Cancelexecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulation en cours....
        /// </summary>
        public static string JobViewModel_CancelToken {
            get {
                return ResourceManager.GetString("JobViewModel_CancelToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les jobs sont terminés.
        /// </summary>
        public static string JobViewModel_JobSuccess {
            get {
                return ResourceManager.GetString("JobViewModel_JobSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string Menu_Option_Home {
            get {
                return ResourceManager.GetString("Menu_Option_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lister les travaux.
        /// </summary>
        public static string Menu_Option1 {
            get {
                return ResourceManager.GetString("Menu_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un travail.
        /// </summary>
        public static string Menu_Option2 {
            get {
                return ResourceManager.GetString("Menu_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter un travail.
        /// </summary>
        public static string Menu_Option3 {
            get {
                return ResourceManager.GetString("Menu_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un travail.
        /// </summary>
        public static string Menu_Option4 {
            get {
                return ResourceManager.GetString("Menu_Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déchiffrer un fichier.
        /// </summary>
        public static string Menu_OptionDecrypt {
            get {
                return ResourceManager.GetString("Menu_OptionDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string Menu_OptionExit {
            get {
                return ResourceManager.GetString("Menu_OptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Menu_OptionSettings {
            get {
                return ResourceManager.GetString("Menu_OptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MENU PRINCIPAL.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune travail de sauvegarde trouvé..
        /// </summary>
        public static string Msg_NoJobs {
            get {
                return ResourceManager.GetString("Msg_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur Entrée pour revenir au menu....
        /// </summary>
        public static string Msg_Return {
            get {
                return ResourceManager.GetString("Msg_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string None2 {
            get {
                return ResourceManager.GetString("None2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à non trouvé.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le mot de passe pour le fichier: .
        /// </summary>
        public static string PasswordRequest {
            get {
                return ResourceManager.GetString("PasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Sauvegarde terminée:.
        /// </summary>
        public static string Savejob_sauvegardefinis {
            get {
                return ResourceManager.GetString("Savejob_sauvegardefinis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au menu principal.
        /// </summary>
        public static string SettingsFlow_BackMenu {
            get {
                return ResourceManager.GetString("SettingsFlow_BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du logiciel (ou vide pour aucun) : .
        /// </summary>
        public static string SettingsFlow_BSoftWareName {
            get {
                return ResourceManager.GetString("SettingsFlow_BSoftWareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel métier modifié avec succès !.
        /// </summary>
        public static string SettingsFlow_BSoftWareSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_BSoftWareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- MODIFICATION DE LA LANGUE ---.
        /// </summary>
        public static string SettingsFlow_Changementlang {
            get {
                return ResourceManager.GetString("SettingsFlow_Changementlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre choix :.
        /// </summary>
        public static string SettingsFlow_Choice {
            get {
                return ResourceManager.GetString("SettingsFlow_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix invalide. Appuyez sur une touche....
        /// </summary>
        public static string SettingsFlow_ChoixErreur {
            get {
                return ResourceManager.GetString("SettingsFlow_ChoixErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quel paramètre souhaitez-vous modifier ?.
        /// </summary>
        public static string SettingsFlow_Choixmodif {
            get {
                return ResourceManager.GetString("SettingsFlow_Choixmodif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur une touche pour continuer ....
        /// </summary>
        public static string SettingsFlow_Continue {
            get {
                return ResourceManager.GetString("SettingsFlow_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions Crypto.
        /// </summary>
        public static string SettingsFlow_Crypto {
            get {
                return ResourceManager.GetString("SettingsFlow_Crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions actuelles :.
        /// </summary>
        public static string SettingsFlow_Encryp_Exten {
            get {
                return ResourceManager.GetString("SettingsFlow_Encryp_Exten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez les extensions séparées par des virgules (ex: .txt,.doc,.pdf) : .
        /// </summary>
        public static string SettingsFlow_EncryptExtenChoice {
            get {
                return ResourceManager.GetString("SettingsFlow_EncryptExtenChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions crypto modifiées avec succès !.
        /// </summary>
        public static string SettingsFlow_EncryptSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_EncryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string SettingsFlow_Language {
            get {
                return ResourceManager.GetString("SettingsFlow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue modifiée avec succès !.
        /// </summary>
        public static string SettingsFlow_LanguageSucessfull {
            get {
                return ResourceManager.GetString("SettingsFlow_LanguageSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Log.
        /// </summary>
        public static string SettingsFlow_LogFormat {
            get {
                return ResourceManager.GetString("SettingsFlow_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de log modifié avec succès !.
        /// </summary>
        public static string SettingsFlow_LogFormatSuccess {
            get {
                return ResourceManager.GetString("SettingsFlow_LogFormatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- MODIFICATION DU LOGICIEL MÉTIER ---.
        /// </summary>
        public static string SettingsFlow_ModifBusinesSoftWare {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifBusinesSoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- MODIFICATION DES EXTENSIONS CRYPTO ---.
        /// </summary>
        public static string SettingsFlow_ModifEncrypt {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- MODIFICATION DU FORMAT DE LOG ---.
        /// </summary>
        public static string SettingsFlow_ModifLogFormat {
            get {
                return ResourceManager.GetString("SettingsFlow_ModifLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à --- PARAMÈTRES ---.
        /// </summary>
        public static string SettingsFlow_Parameters {
            get {
                return ResourceManager.GetString("SettingsFlow_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priorités.
        /// </summary>
        public static string SettingsFlow_Priorities {
            get {
                return ResourceManager.GetString("SettingsFlow_Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel métier.
        /// </summary>
        public static string SettingsFlow_SoftwareBuis {
            get {
                return ResourceManager.GetString("SettingsFlow_SoftwareBuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrage.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source, destination et mot de passe ne peuvent pas être vides..
        /// </summary>
        public static string ThrowWrongInput {
            get {
                return ResourceManager.GetString("ThrowWrongInput", resourceCulture);
            }
        }
    }
}
